Fixed tag and publish scripts

diff --git a/scripts/image-publish b/scripts/image-publish
--- a/scripts/image-publish
+++ b/scripts/image-publish
@@ -23,6 +23,20 @@ if [ -f "./.envs.conf" ] ; then
 fi
 set +a
 
+if [ -z $PUBLISH_REPOSITORY ] ; then
+ echo "PUBLISH_REPOSITORY not found"
+ exit 1
+fi
+
+if [ -z $DOCKERIO_USERNAME ] ; then
+ echo "DOCKERIO_USERNAME not found"
+ exit 1
+fi
+
+if [ -z $DOCKERIO_PASSWORD ] ; then
+ echo "DOCKERIO_PASSWORD not found"
+ exit 1
+fi
 
 LOGIN="podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD $PUBLISH_REPOSITORY"
 # DO NOT LEAVE THIS UNCOMMENTED
diff --git a/scripts/image-tag b/scripts/image-tag
--- a/scripts/image-tag
+++ b/scripts/image-tag
@@ -21,6 +21,16 @@ if [ -f "./.envs.conf" ] ; then
 fi
 set +a
 
+if [ -z $PUBLISH_REPOSITORY ] ; then
+ echo "PUBLISH_REPOSITORY not found"
+ exit 1
+fi
+
+if [ -z $DOCKERIO_USERNAME ] ; then
+ echo "DOCKERIO_USERNAME not found"
+ exit 1
+fi
+
 TAG="podman tag 'localhost/$_NAME:build' '$PUBLISH_REPOSITORY/$DOCKERIO_USERNAME/$_NAME:$1'"
 echo "$TAG"
 /bin/sh -c "$TAG"
